---
title: "Day-7 Python And Basic Grammar"
output:
  html_document:
    keep_md: true
date: '2022-06-28'
---

# Python Basic Grammer

## 반복문


### for loop

In [2]:
for i in range(3):
  print("Hello World")

Hello World
Hello World
Hello World


- 리스트 총합 구하기

In [5]:
number = [1,2,3,4,5]
sum=0

for num in number:
  print("number: ",num)
  sum = sum + num
  print("total: ",sum)
  

number:  1
total:  1
number:  2
total:  3
number:  3
total:  6
number:  4
total:  10
number:  5
total:  15


### while loop

- 분석할 때 거의 쓸 일이 없음

In [19]:
i=0
while i<10:
  i+=1
  print(i)


1
2
3
4
5
6
7
8
9
10


## 사용자 정의 함수
- 내가 필요에 의해서 직접 함수를 작성

In [30]:
def 함수명(param1, param2):
  #코드
  return None

- 사칙연산

In [43]:
def add(a=0, b=1):
  c = a + b 
  return c
  #return  a + b
print(add(a=5,b=4))
print(add()) 

9
1


In [53]:
def x(a=2,b=3,d=5):
  c = a * b 
  return c
print(x(5,3,2))

15


In [51]:
def y(a=2,b=3):
  c = a/b
  return c
print(y(10,3))

3.3333333333333335


In [50]:
def z(a=3,b=5):
  c=a-b
  return c
print(z(10,3)) 

7


### 함수 문서화

- Docstring


In [57]:
def subtract(a,b):
  """a,b를 빼는 함수
  Parameters:
  a(int): int형 숫자 a가 입력
  b(int): int형 숫자 a가 입력
  Returns:
    int:반환값
  """
  return a-b
print(subtract(5,10))
print(subtract.__doc__)

-5
a,b를 빼는 함수
  Parameters:
  a(int): int형 숫자 a가 입력
  b(int): int형 숫자 a가 입력
  Returns:
    int:반환값
  


## Numpy

- 숫자계산을 위해 나온 라이브러리
- 리스트 -> 행렬(배열)로 변환
  - (2,3) : 2행 3열, (3,2) : 3행 2열


In [60]:
import numpy as np
print(np.__version__)

1.21.6


In [65]:
temp=[1,2,3]
temp_array = np.array(temp) # 리스트에서 배열로 numpy를 사용해서 변환
print(type(temp))
print(type(temp_array))

<class 'list'>
<class 'numpy.ndarray'>


### 사칙연산

In [72]:
math_score = [90,30,50]
eng_score = [80,90,100]

math_array = np.array(math_score) # math_score의 리스트타입을 배열타입으로 변환
eng_array = np.array(eng_score) # eng_score의 리스트타입을 배열타입으로 변환

total = math_array + eng_array
print(total)
print(type(total))

[170 120 150]
<class 'numpy.ndarray'>


### 집계함수

In [74]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

120
170
440


### 차원 확인
- 배열의 차원 확인 필요

In [80]:
# 1차원
temp_arr = np.array([1,2,3])
print(temp_arr.shape) # 1차원임을 보여줌
print(temp_arr.ndim) # n차원에서 n을 출력
print(temp_arr)

(3,)
1
[1 2 3]


In [82]:
temp_arr = np.array([[1,2,3],[4,5,6]])
print(temp_arr.shape) # 2차원임을 보여줌(2행,3열)
print(temp_arr.ndim) # n차원에서 n을 출력
print(temp_arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [84]:
# 3차원 배열 -> 이미지
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],[[13,14,15],[16,17,18]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(3, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


### 배열 생성의 다양한 방법
- 모두 0으로 채운다.

In [1]:
import numpy as np
print(np.__version__)

1.21.6


In [3]:
temp_arr = np.zeros((3,4,2))
temp_arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

- 모두 1로 채운다.

In [5]:
temp_arr = np.ones((3,4,2))
temp_arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

- 임의의 상수값으로 채운다

In [7]:
temp_arr = np.full((3,4,2), 5)
temp_arr

array([[[5, 5],
        [5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5],
        [5, 5]]])

- 최소, 최대 숫자의 범위를 정해두고 각 구간별로 값을 생

In [8]:
temp_arr = np.linspace(5,10,10) #5~10까지의 랜덤수 10개
temp_arr

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시, 자주 등장하는 배

In [12]:
temp_arr = np.arange(1,11,2) # 1이상 ~ 11미만 까지의 숫자를 2의 간격을 둔다
temp_arr

array([1, 3, 5, 7, 9])

### 난수생성


In [17]:
from numpy import random # numpy라는 class안에 random이라는 매쏘드가 들어간다. 
x= random.rand()
print(x)

0.552080448226351


In [18]:
import numpy
x=numpy.random.rand()
print(x)

0.41225321175073026


- 랜덤 정수값 추출 

In [28]:
from numpy import random
x=random.randint(100, size=(5,6)) # x < 100인 값 5개 추출
print(x)
print(type(x)) # 배열

[[46 87 90 36 81 57]
 [ 1 80 91 13 37 85]
 [25 44 52 67 47 65]
 [ 6 49 92 22 56 77]
 [67 11 48 74 53 19]]
<class 'numpy.ndarray'>


- 랜덤 실수값 배열 추

In [32]:
from numpy import random
x=random.rand(3,4)
print(x)
print(type(x))

[[0.91807102 0.25931888 0.30310341 0.38788609]
 [0.97937962 0.59220515 0.00528968 0.74546826]
 [0.64986126 0.19483289 0.19125284 0.8947326 ]]
<class 'numpy.ndarray'>


### 사칙연산


In [33]:
import numpy as np
array_01 = np.array([1,2,3])
array_02 = np.array([10,20,30])

In [37]:
# 덧셈
newArr=np.add(array_01, array_02)
print(newArr)
# 뺄셈
newArr=np.subtract(array_01, array_02)
print(newArr)
# 곱셈
newArr=np.multiply(array_01, array_02)
print(newArr)
# 나눗셈
newArr=np.divide(array_01, array_02)
print(newArr)
# 거듭제곱
array_01 = np.array([1,2,3])
array_02 = np.array([2,4,3])
newArr=np.power(array_01, array_02)
print(newArr)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[ 1 16 27]


### 소숫점 정렬 


In [39]:
import numpy as np
# 소숫점 제거
temp_arr = np.trunc([-1.23,12.3])
print(temp_arr)
temp_arr = np.fix([-1.23,12.3])
print(temp_arr)

[-1. 12.]
[-1. 12.]


In [42]:
# 임의의 소숫점자리에서 반올림
temp_arr = np.around([-1.23456,12.34567],3) # 3의 자리까지 표시(4의자리에서 반올림)
print(temp_arr)

[-1.235 12.346]


In [43]:
# 소숫점 모두내림
temp_arr = np.floor([-1.23456,12.34567])
print(temp_arr)

[-2. 12.]


In [46]:
# 소숫점 모두올림
temp_arr = np.ceil([-1.23456,12.34567],)
print(temp_arr)

[-1. 13.]


### 조건식
- 하나의 조건식
  - np.where(조건식, 참일때, 거짓일때)


In [48]:
temp_arr=np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# 5보다 작으면 원값유지
# 5보다 크면 *10

In [53]:
np.where(temp_arr < 5, temp_arr, temp_arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

- 다중 조건식
  - np.select(조건식 리스트, 결괏값 리스트, default =)

In [59]:
temp_arr=np.arange(10)
# temp_arr
cond_list   = [temp_arr > 5, temp_arr < 2]  # 조건식 리스트 [첫번째조건,  두번째조건  ,...]
choice_list = [temp_arr * 2, temp_arr + 100]# 결괏값 리스트 [첫번째결괏값,두번째결괏값,...]

np.select(cond_list, choice_list, default = temp_arr) # 조건식리스트가 먼저, 결괏값 리스트는 뒤에

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

### Reshape 
- 배열의 차원 또는 크기를 변경

In [61]:
import numpy as np
temp_array = np.ones((3,4)) # 3*4=12
print(temp_array.shape)
print(temp_array)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [67]:
after_reshape = temp_array.reshape(2,6) # 원래 배열의 크기만 맞춰주면 된다. 2*6=12
print(after_reshape.shape)
print(after_reshape)

(2, 6)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [68]:
after_reshape = temp_array.reshape(2,2,3) # 원래 배열의 크기만 맞춰주면 된다. 2*2*3=12
print(after_reshape.shape)
print(after_reshape)

(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [69]:
after_reshape = temp_array.reshape(2,2,-1) # 크기가 커서 계산을 못할때 -1을 넣는다.
print(after_reshape.shape)
print(after_reshape)

(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 브로드 캐스팅
- 서로 다른 크기의 배열을 계산할 때의 기본적인 규칙


## pandas 튜토리얼


In [75]:
import pandas as pd
print(pd.__version__)

1.3.5


In [78]:
temp_dict = {
    'col1' : [1,2],
    'col2' : [3,4]
}

df = pd.DataFrame(temp_dict)
print(df)
print(type(df))

   col1  col2
0     1     3
1     2     4
<class 'pandas.core.frame.DataFrame'>


### 구글 드라이브 연동 

In [79]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [86]:
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/human_AI/Basic/Chapter 3. pandas/data/'
lemonade = pd.read_csv(DATA_PATH + 'Lemonade2016.csv')
# covid_df = pd.read_csv(DATA_PATH + 'owid-covid-data.csv')

lemonade.info() # str()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB


## Practice


- while문을 사용해 1부터 1000까지의 자연수 중 3의배수의 합을 구해보자

In [87]:
result = 0
i=1
while i <= 1000:
  if i%3 == 0:
    result += i
  i+=1
print(result)  
  

166833


- while문을 사용하여 다음과 같이 별(*)을 표시하는 프로그램을 작성해보자

In [103]:
i=0
input1 = int(input("숫자입력")) # 입력된 숫자를 실수로 바꿔준다
while i < input1 : # 별의 갯수가 입력한 숫자가 될때까지 출력
  i+=1
  print('*' *i)


숫자입력3
*
**
***


- for문을 사용해 1부터 30까지의 숫자를 출력해보자

In [99]:
for i in range(1,31):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


- A학급에 총 10명의 학생이 있다. 이 학생들의 중간고사 점수는 다음과같아. [70,60,55,75,95,90,80,80,85,100] for 문을 이용하여 a학급의 평균점수를 구해보자.

In [95]:
mid_score = [70,60,55,75,95,90,80,80,85,100] # type:list
total = 0   # type : int 
for i in mid_score:
  total += i      
  avg = total/len(mid_score) # type:int
print(avg)

79.0


- 리스트 중에서 홀수에만 2를 곱하여 저장하는 다음코드가 있다.
```
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2) 
```
위 코드를 리스트내포를 사용하여 표현해보자

In [96]:
numbers = [1,2,3,4,5]
result = [n*2 for n in numbers if n%2 == 1]
print(result)

[2, 6, 10]


- 1~50까지의 수에서 2의 배수일때 'Buzz', 11의 배수일때는 'Fizz', 2와 11의 공배수일때는 'BuzzFizz'가 되도록 출력하라

In [98]:
for i in range(1,51):
  if i % 2 == 0 | i % 11 == 0:
    print('BuzzFizz')
  elif i % 2 == 0:
    print('Buzz')
  elif i % 11 == 0:
    print('fizz')
  else:
    print(i)    

1
Buzz
3
Buzz
5
Buzz
7
Buzz
9
Buzz
fizz
Buzz
13
Buzz
15
Buzz
17
Buzz
19
Buzz
21
BuzzFizz
23
Buzz
25
Buzz
27
Buzz
29
Buzz
31
Buzz
fizz
Buzz
35
Buzz
37
Buzz
39
Buzz
41
Buzz
43
BuzzFizz
45
Buzz
47
Buzz
49
Buzz
